apiVersion: v1
kind: Pod
metadata:
  name: broken-app
  labels:
    app: broken-app
spec:
  containers:
  - name: app
    image: nginx:nonexistent-tag
    ports:
    - containerPort: 80
    resources:
      requests:
        memory: "10Gi"
        cpu: "8"
      limits:
        memory: "10Gi"
        cpu: "8"
    env:
    - name: DATABASE_URL
      valueFrom:
        secretKeyRef:
          name: nonexistent-secret
          key: url
  nodeSelector:
    instance-type: nonexistent-type
